apiVersion: apps/v1
kind: Deployment
metadata:
 name: spring
spec: 
 selector:
  matchiabels:
    app: spring
 template: 
   metadata:
     labels:
       app: spring
   spec: 
      containers:
      - name: springserver
        image: rakesh9657/demo:latest
        ports:
        - containerPort: 8085
        
        
        
 apiVersion: v1
 kind: Service
 metadata: 
   name: spring-service
 spec: 
   selectors:
      app: spring
   ports: 
    - protocol: "TCP"
      port: 8085
      targetPort: 8085
   type: NodePort